<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Course_fa fa-money</name>
   <tag></tag>
   <elementGuidId>07be0866-40c2-4019-b1b0-bef502366726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p[@id='rcorners2']/i)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-money</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0d390ea1-ed3d-4509-ba28-51eea65228ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-money</value>
      <webElementGuid>ab86e9a8-2aba-4e10-8de0-f8e9a784abfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d6d00e15-6acc-4282-aac5-a1fd395ae36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/table[2]/tbody[1]/tr[2]/td[2]/table[1]/tbody[1]/tr[1]/td[3]/a[1]/p[@id=&quot;rcorners2&quot;]/i[@class=&quot;fa fa-money&quot;]</value>
      <webElementGuid>bc22861c-06c3-4399-bb18-8949d424855b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//p[@id='rcorners2']/i)[3]</value>
      <webElementGuid>642dc7be-8a96-4c3a-9fe1-2a146e6ee21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/p/i</value>
      <webElementGuid>608d9e54-426d-48c1-9e67-9f77c89b9d17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
