<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_44986820</name>
   <tag></tag>
   <elementGuidId>0025fa59-2860-4210-9b88-d4853164942e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='TransNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TransNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>32de64a5-8c60-40ac-97bc-33a283e2ad60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TransNo</value>
      <webElementGuid>32dfeab9-4d9b-40ff-b5cf-cc67c21c25e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>44986820</value>
      <webElementGuid>ef0d43e1-42d8-4bf7-a2b4-2787d5e1786b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TransNo&quot;)</value>
      <webElementGuid>fd0a464f-7ee0-4e89-90be-d59432258699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='TransNo']</value>
      <webElementGuid>400c7cf0-ec99-4522-aed1-535061e7d783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'TransNo', '&quot;', ')')])[1]/preceding::p[1]</value>
      <webElementGuid>90ca9ec0-6c1a-445a-9fe3-fe829f53ead3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='44986820']/parent::*</value>
      <webElementGuid>054fa9b9-a857-4447-acf7-b33f692bdb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>c83af3fd-50fa-413f-a641-9c9acc680177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'TransNo' and (text() = '44986820' or . = '44986820')]</value>
      <webElementGuid>19b1206d-859b-4312-b9b5-7de0927ffb0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
